from fastapi.responses import FileResponse
from typing import Dict, Any
from ase.io import write
import tempfile
import pickle
import numpy as np
from .serialization import atoms_to_json

def _apply_payload_positions(session, payload: Dict[str, Any]):
    if payload and "positions" in payload:
        session.working_atoms.set_positions(
            np.array(payload["positions"]),
            apply_constraint=bool(payload.get("apply_constraint", True)),
        )
    return session.working_atoms
 
def _atoms_for_vasp_export(atoms):
    if atoms.cell.rank == 3:
        return atoms

    export_atoms = atoms.copy()
    export_atoms.calc = None
    export_atoms.center(vacuum=8.0)
    export_atoms.set_pbc([False, False, False])
    return export_atoms


def export_poscar_response(session, payload: Dict[str, Any]):
    atoms = _apply_payload_positions(session, payload)
    tmp = tempfile.NamedTemporaryFile(delete=False, suffix=".vasp")
    tmp.close()
    write(tmp.name, _atoms_for_vasp_export(atoms), format="vasp")
    return FileResponse(tmp.name, filename="POSCAR", media_type="application/octet-stream")


def export_pickle_response(session, payload: Dict[str, Any]):
    _apply_payload_positions(session, payload)
    include_calc = payload.get("include_calculator", False)

    atoms_to_save = session.working_atoms.copy()
    if not include_calc:
        atoms_to_save.calc = None

    tmp = tempfile.NamedTemporaryFile(delete=False, suffix=".pkl")
    tmp.close()
    try:
        with open(tmp.name, "wb") as handle:
            pickle.dump(atoms_to_save, handle)
    except Exception as exc:
        if include_calc:
            atoms_to_save.calc = None
            with open(tmp.name, "wb") as handle:
                pickle.dump(atoms_to_save, handle)
        else:
            raise exc
    return FileResponse(tmp.name, filename="atoms.pkl", media_type="application/octet-stream")


def _trajectory_frames_json(session):
    frames = getattr(session, "trajectory_frames", []) or []
    if len(frames) <= 1:
        return []
    return [atoms_to_json(frame) for frame in frames]


def _blender_script(data: Dict[str, Any]) -> str:
    return f'''# Generated by v_ase. Run in Blender with: blender --python this_file.py
import math
import bpy
from mathutils import Vector

DATA = {repr(data)}
FRAMES = DATA.get("frames", [])

VISUAL = DATA.get("visual", {{}})
ATOM_COLORS = VISUAL.get("colors", [])
ATOM_RADII = VISUAL.get("radii", VISUAL.get("covalent_radii", []))
FALLBACK_COLOR = (0.8, 0.8, 0.8, 1.0)
FALLBACK_RADIUS = 0.7

def clamp01(value):
    return max(0.0, min(1.0, float(value)))

def hex_to_rgba(value):
    if isinstance(value, str):
        text = value.strip().lstrip("#")
        if len(text) == 6:
            try:
                return (
                    int(text[0:2], 16) / 255.0,
                    int(text[2:4], 16) / 255.0,
                    int(text[4:6], 16) / 255.0,
                    1.0,
                )
            except ValueError:
                pass
    if isinstance(value, (list, tuple)) and len(value) >= 3:
        return (clamp01(value[0]), clamp01(value[1]), clamp01(value[2]), clamp01(value[3]) if len(value) > 3 else 1.0)
    return FALLBACK_COLOR

def get_atom_color(index):
    if 0 <= index < len(ATOM_COLORS):
        return hex_to_rgba(ATOM_COLORS[index])
    return FALLBACK_COLOR

def get_atom_radius(index, fallback=FALLBACK_RADIUS):
    if 0 <= index < len(ATOM_RADII):
        try:
            radius = float(ATOM_RADII[index])
            if radius > 0:
                return radius
        except (TypeError, ValueError):
            pass
    return fallback

def material(name, color, alpha=1.0):
    mat = bpy.data.materials.new(name)
    mat.diffuse_color = color
    if alpha < 1.0:
        mat.use_nodes = True
        bsdf = mat.node_tree.nodes.get("Principled BSDF")
        bsdf.inputs["Alpha"].default_value = alpha
        mat.blend_method = "BLEND"
        mat.show_transparent_back = True
    return mat

ATOM_MATS = {{}}
MAT_LINE = material("v_ase fixed line", (0.3, 0.8, 1.0, 0.55), 0.55)
MAT_PLANE = material("v_ase fixed plane", (0.25, 1.0, 0.78, 0.22), 0.22)
MAT_HOOKEAN = material("v_ase Hookean active spring", (1.0, 0.58, 0.18, 1.0), 1.0)
MAT_HOOKEAN_INACTIVE = material("v_ase Hookean inactive spring", (0.56, 0.72, 1.0, 0.48), 0.48)
MAT_HOOKEAN_GUIDE = material("v_ase Hookean threshold guide", (0.68, 0.76, 0.85, 0.42), 0.42)
MAT_HOOKEAN_HOOK = material("v_ase Hookean hook latch", (0.48, 0.72, 1.0, 0.86), 0.86)
MAT_HOOKEAN_SLACK = material("v_ase Hookean inactive gap", (0.72, 0.76, 0.85, 0.38), 0.38)
MAT_HOOKEAN_ACTIVE_MARKER = material("v_ase Hookean active marker", (0.22, 0.85, 0.59, 0.92), 0.92)
MAT_HOOKEAN_INACTIVE_MARKER = material("v_ase Hookean inactive marker", (0.46, 0.66, 1.0, 0.78), 0.78)
MAT_HOOKEAN_THRESHOLD_MARKER = material("v_ase Hookean threshold marker", (1.0, 0.82, 0.35, 0.9), 0.9)

def get_atom_mat(index, symbol):
    color = get_atom_color(index)
    key = f"{{symbol}}_{{color[0]:.4f}}_{{color[1]:.4f}}_{{color[2]:.4f}}"
    if key not in ATOM_MATS:
        ATOM_MATS[key] = material(f"atom {{symbol}}", color, 1.0)
    return ATOM_MATS[key]

def look_at_axis(obj, direction):
    direction = Vector(direction)
    if direction.length == 0:
        return
    quat = direction.to_track_quat("Z", "Y")
    obj.rotation_euler = quat.to_euler()

def add_cylinder_between(name, start, end, radius, mat):
    start = Vector(start); end = Vector(end)
    mid = (start + end) * 0.5
    length = (end - start).length
    if length <= 1e-8:
        return None
    bpy.ops.mesh.primitive_cylinder_add(vertices=24, radius=radius, depth=length, location=mid)
    obj = bpy.context.object
    obj.name = name
    look_at_axis(obj, end - start)
    obj.data.materials.append(mat)
    return obj

def add_plane_disc(name, center, normal, radius, mat):
    bpy.ops.mesh.primitive_circle_add(vertices=96, radius=radius, fill_type="TRIFAN", location=center)
    obj = bpy.context.object
    obj.name = name
    look_at_axis(obj, normal)
    obj.data.materials.append(mat)
    return obj

def add_poly_curve(name, points, mat, bevel=0.025):
    curve = bpy.data.curves.new(name, "CURVE")
    curve.dimensions = "3D"
    curve.resolution_u = 3
    curve.bevel_depth = bevel
    poly = curve.splines.new("POLY")
    poly.points.add(len(points) - 1)
    for idx, p in enumerate(points):
        poly.points[idx].co = (p.x, p.y, p.z, 1.0)
    obj = bpy.data.objects.new(name, curve)
    bpy.context.collection.objects.link(obj)
    obj.data.materials.append(mat)
    return obj

def add_ring(name, center, direction, radius, mat):
    bpy.ops.mesh.primitive_torus_add(major_radius=radius, minor_radius=radius * 0.12, major_segments=48, minor_segments=8, location=center)
    obj = bpy.context.object
    obj.name = name
    look_at_axis(obj, direction)
    obj.data.materials.append(mat)
    return obj

def hookean_state(length, threshold):
    if threshold is None or threshold <= 0:
        return "active"
    if abs(length - threshold) <= max(0.035, threshold * 0.025):
        return "threshold"
    return "inactive" if length < threshold else "active"

def hookean_marker_material(state):
    if state == "active":
        return MAT_HOOKEAN_ACTIVE_MARKER
    if state == "threshold":
        return MAT_HOOKEAN_THRESHOLD_MARKER
    return MAT_HOOKEAN_INACTIVE_MARKER

def add_hookean_spring(name, start, end, threshold=None, radius_start=0.7, radius_end=0.7):
    start = Vector(start); end = Vector(end)
    axis = end - start
    length = axis.length
    if length <= 1e-8:
        return None
    direction = axis.normalized()
    helper = direction.cross(Vector((0, 0, 1)))
    if helper.length < 1e-6:
        helper = direction.cross(Vector((0, 1, 0)))
    u = helper.normalized()
    v = direction.cross(u).normalized()
    center = (start + end) * 0.5

    def to_world(x, y, z=0.0):
        return center + direction * y + u * x + v * z

    left_center = -length / 2
    right_center = length / 2
    left = left_center + min(radius_start * 0.55 + 0.04, length * 0.24)
    right = right_center - min(radius_end * 0.55 + 0.04, length * 0.24)
    span = max(0.12, abs(right - left))
    state = hookean_state(length, threshold)
    gate_width = max(0.12, min(span * 0.09, 0.28))
    lock_half = max(0.08, min(span * 0.045, 0.18))
    threshold_y = left_center + threshold if threshold and threshold > 0 else left + span * 0.52
    spring_start = threshold_y
    spring_end = right
    spring_len = max(0.001, spring_end - spring_start)
    amplitude = min(0.16, span * 0.08)
    coils = max(6, round(5 + spring_len * 2.2))
    steps = max(8, coils * 2)

    add_poly_curve(name + "_dead_zone_rail", [
        to_world(0, left, 0),
        to_world(0, threshold_y, 0),
    ], MAT_HOOKEAN_GUIDE, bevel=0.018)

    add_poly_curve(name + "_cutoff_gate", [
        to_world(-gate_width, threshold_y, 0),
        to_world(gate_width, threshold_y, 0),
    ], hookean_marker_material(state), bevel=0.024 if state == "inactive" else 0.034)

    if state != "inactive":
        add_poly_curve(name + "_lock_pin", [
            to_world(0, threshold_y - lock_half, 0),
            to_world(0, threshold_y + lock_half, 0),
        ], hookean_marker_material(state), bevel=0.034)

    if state != "inactive" and spring_end > spring_start:
        spring_points = [to_world(0, spring_start, 0)]
        for step in range(1, steps):
            t = step / steps
            x = amplitude if step % 2 else -amplitude
            spring_points.append(to_world(x, spring_start + (spring_end - spring_start) * t, 0))
        spring_points.append(to_world(0, spring_end, 0))
        add_poly_curve(name + "_spring", spring_points, MAT_HOOKEAN)

    if state == "inactive" and threshold_y > right:
        add_poly_curve(name + "_inactive_gap", [to_world(0, right, 0), to_world(0, threshold_y, 0)], MAT_HOOKEAN_SLACK, bevel=0.015)
    return None

bpy.ops.object.select_all(action="SELECT")
bpy.ops.object.delete()

positions = DATA["positions"]
symbols = DATA["symbols"]
atoms = []
for idx, (symbol, pos) in enumerate(zip(symbols, positions)):
    bpy.ops.mesh.primitive_uv_sphere_add(segments=32, ring_count=16, radius=get_atom_radius(idx), location=pos)
    obj = bpy.context.object
    obj.name = f"atom_{{idx:04d}}_{{symbol}}"
    obj.data.materials.append(get_atom_mat(idx, symbol))
    atoms.append(obj)

def frame_topology_matches(frame_data):
    return (
        frame_data.get("symbols") == symbols
        and len(frame_data.get("positions", [])) == len(atoms)
    )

if len(FRAMES) > 1 and all(frame_topology_matches(frame) for frame in FRAMES):
    bpy.context.scene.frame_start = 1
    bpy.context.scene.frame_end = len(FRAMES)
    for frame_number, frame_data in enumerate(FRAMES, start=1):
        for idx, obj in enumerate(atoms):
            obj.location = frame_data["positions"][idx]
            obj.keyframe_insert(data_path="location", frame=frame_number)
    for obj in atoms:
        if obj.animation_data and obj.animation_data.action:
            for fcurve in obj.animation_data.action.fcurves:
                for keyframe in fcurve.keyframe_points:
                    keyframe.interpolation = "LINEAR"

constraints = DATA.get("constraints", {{}})
for idx_text, direction in constraints.get("fixed_line", {{}}).items():
    idx = int(idx_text)
    start = Vector(positions[idx]) - Vector(direction).normalized() * 2.2
    end = Vector(positions[idx]) + Vector(direction).normalized() * 2.2
    add_cylinder_between(f"fixed_line_{{idx}}", start, end, 0.035, MAT_LINE)

for idx_text, normal in constraints.get("fixed_plane", {{}}).items():
    idx = int(idx_text)
    add_plane_disc(f"fixed_plane_{{idx}}", positions[idx], normal, 1.6, MAT_PLANE)

for item in constraints.get("hookean", []):
    if item.get("kind") == "two atoms":
        i, j = item["indices"]
        add_hookean_spring(
            f"hookean_{{i}}_{{j}}",
            positions[i],
            positions[j],
            threshold=item.get("threshold"),
            radius_start=get_atom_radius(i),
            radius_end=get_atom_radius(j),
        )
    elif item.get("kind") == "point":
        idx = item["index"]
        add_hookean_spring(
            f"hookean_{{idx}}_point",
            positions[idx],
            item["origin"],
            threshold=item.get("threshold"),
            radius_start=get_atom_radius(idx),
            radius_end=0.18,
        )
    elif item.get("kind") == "plane":
        idx = item["index"]
        A, B, C, D = item["plane"]
        normal = Vector((A, B, C))
        pos = Vector(positions[idx])
        signed = (A * pos.x + B * pos.y + C * pos.z + D) / max(normal.length, 1e-9)
        center = pos - normal.normalized() * signed
        add_plane_disc(f"hookean_plane_{{idx}}", center, normal, 1.25, MAT_PLANE)
        add_hookean_spring(
            f"hookean_{{idx}}_plane_spring",
            pos,
            center,
            threshold=None,
            radius_start=get_atom_radius(idx),
            radius_end=0.18,
        )

bpy.ops.object.light_add(type="AREA", location=(5, -6, 8))
bpy.context.object.name = "v_ase_area_light"
bpy.context.object.data.energy = 450
bpy.context.object.data.size = 5
bpy.ops.object.camera_add(location=(8, -9, 6), rotation=(math.radians(60), 0, math.radians(42)))
bpy.context.scene.camera = bpy.context.object
'''


def export_blender_response(session, payload: Dict[str, Any]):
    atoms = _apply_payload_positions(session, payload)
    if getattr(session, "trajectory_frames", None):
        session.sync_current_frame()
    data = atoms_to_json(atoms)
    frames = _trajectory_frames_json(session)
    if frames:
        data["frames"] = frames
    tmp = tempfile.NamedTemporaryFile(delete=False, suffix="_v_ase_blender.py", mode="w", encoding="utf-8")
    tmp.write(_blender_script(data))
    tmp.close()
    return FileResponse(tmp.name, filename="v_ase_blender_scene.py", media_type="text/x-python")
