"""Generate Open With registration without taking ownership of structure types."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def nsis_source(extensions, legacy_generic_extensions=()):
    lines = [
        '; Generated by scripts/generate_file_associations.py. Do not edit by hand.',
        '; Only the separate .vase association is a default. Never write UserChoice.',
        '!macro customInstall',
        '  WriteRegStr SHELL_CONTEXT "Software\\Classes\\org.v-ase.structure" "" "Atomic structure"',
        '  WriteRegStr SHELL_CONTEXT "Software\\Classes\\org.v-ase.structure" "AllowSilentDefaultTakeOver" ""',
        '  WriteRegStr SHELL_CONTEXT "Software\\Classes\\org.v-ase.structure\\DefaultIcon" "" \'"$INSTDIR\\resources\\file-icons\\structure-document.ico"\'',
        '  WriteRegStr SHELL_CONTEXT "Software\\Classes\\org.v-ase.structure\\shell\\open\\command" "" \'"$INSTDIR\\${APP_EXECUTABLE_FILENAME}" "%1"\'',
    ]
    # Remove only our old Open With registration on upgrade. Never choose a
    # replacement default for a user's JSON, HTML or other general document.
    lines += [f'  DeleteRegValue SHELL_CONTEXT "Software\\Classes\\.{ext}\\OpenWithProgids" "org.v-ase.structure"' for ext in legacy_generic_extensions]
    lines += [f'  WriteRegNone SHELL_CONTEXT "Software\\Classes\\.{ext}\\OpenWithProgids" "org.v-ase.structure"' for ext in extensions]
    lines += ['  System::Call "shell32::SHChangeNotify(i,i,i,i) (0x08000000, 0, 0, 0)"', '!macroend', '', '!macro customUnInstall']
    lines += [f'  DeleteRegValue SHELL_CONTEXT "Software\\Classes\\.{ext}\\OpenWithProgids" "org.v-ase.structure"' for ext in extensions]
    lines += ['  DeleteRegKey SHELL_CONTEXT "Software\\Classes\\org.v-ase.structure"', '  System::Call "shell32::SHChangeNotify(i,i,i,i) (0x08000000, 0, 0, 0)"', '!macroend', '']
    return '\n'.join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    formats = json.loads((ROOT / 'file-formats.json').read_text())
    extensions = formats['structureExtensions']
    config = json.loads((ROOT / 'package.json').read_text())['build']
    assert config['mac']['fileAssociations'][0]['ext'] == extensions, 'Synchronize Mac candidate extensions'
    assert config['mac']['fileAssociations'][0]['rank'] == 'None'
    assert [item['ext'] for item in config['fileAssociations']] == ['vase']
    target = ROOT / 'assets/file-associations.nsh'
    content = nsis_source(extensions, formats['legacyGenericExtensions'])
    if args.check:
        assert target.read_text() == content, 'Regenerate Windows file associations'
    else:
        target.write_text(content)


if __name__ == '__main__':
    main()
