"""Extract documented stills from canonical GIFs and package small example inputs.

Run from a source checkout after capture_readme_screenshots.py. No synthetic
overlays or new camera poses are introduced into the extracted images.
"""
from pathlib import Path
import hashlib
import json
import shutil
import sys

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
ASSETS = ROOT / "docs" / "assets"
# Frame indices refer to decoded GIF frames (duplicate holds may be merged).
STILLS = {
    "html-preview": ("html_quicklook", 0, None),
    "move-start": ("fixedline", 0, (160, 160, 1700, 790)),
    "move-positive": ("fixedline", 8, (160, 160, 1700, 790)),
    "move-negative": ("fixedline", 25, (160, 160, 1700, 790)),
    "rotate-start": ("ferrocene_pivot", 0, (390, 95, 1915, 970)),
    "rotate-z": ("ferrocene_pivot", 14, (390, 95, 1915, 970)),
    "rotate-x": ("ferrocene_pivot", 43, (390, 95, 1915, 970)),
    "plane-start": ("fixedplane", 0, (165, 100, 1915, 1000)),
    "plane-move": ("fixedplane", 19, (165, 100, 1915, 1000)),
    "twist-select": ("phosphorene_twist", 20, (0, 60, 1915, 1000)),
    "twist-rotate": ("phosphorene_twist", 41, (0, 60, 1915, 1000)),
    "twist-result": ("phosphorene_twist", 62, (0, 60, 1915, 1000)),
}


def main():
    output = ASSETS / "steps"
    output.mkdir(exist_ok=True)
    manifest = []
    for name, (scene, index, crop) in STILLS.items():
        source = ASSETS / f"readme_{scene}.gif"
        with Image.open(source) as gif:
            elapsed = 0
            for frame in range(index + 1):
                gif.seek(frame)
                if frame < index:
                    elapsed += gif.info.get("duration", 0)
            gif.convert("RGB").crop(crop).save(output / f"{name}.png", optimize=True)
        manifest.append({"file": f"{name}.png", "source": source.name,
                         "source_sha256": hashlib.sha256(source.read_bytes()).hexdigest(),
                         "frame": index, "time_ms": elapsed, "crop": crop})
    (output / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")

    from ase.io import write
    from examples import readme_scenes as scenes

    examples = ASSETS / "examples"
    examples.mkdir(exist_ok=True)
    for source in (ROOT / "examples" / "readme_scene_assets").iterdir():
        if source.suffix in (".traj", ".cif", ".vasp", ".extxyz"):
            shutil.copyfile(source, examples / source.name)
    for source in (ROOT / "examples" / "commensurate_host_guest").glob("*.extxyz"):
        shutil.copyfile(source, examples / source.name)
    appearance, groups = scenes.make_cu5o4_appearance_scene()
    write(examples / "cu5o4-labeled.extxyz", appearance)
    (examples / "cu5o4-groups.json").write_text(json.dumps(groups, indent=2) + "\n")
    for filename, factory in (
        ("oxygen-insertion.json", scenes.make_random_addition_scene),
        ("water-insertion.json", scenes.make_layered_water_channel_scene),
    ):
        _, settings = factory()
        (examples / filename).write_text(json.dumps(settings, indent=2,
            default=lambda value: value.tolist()) + "\n")
    write(examples / "stored-forces.traj", scenes.make_atom_colorscale_trajectory())
    rdf_atoms = scenes.make_amorphous_cuzr_rdf_scene()
    write(examples / "cuzr-rdf.traj", rdf_atoms)
    atoms, values = scenes.make_graphene_pi_volumetric_scene()
    # Cube uses atomic units for grid vectors. ASE handles that conversion.
    write(examples / "graphene-pi.cube", atoms, data=values)
    (examples / "README.txt").write_text(
        "v_ase documentation examples\n"
        "Generated by scripts/build_docs_walkthrough_assets.py.\n"
        "The graphene pi field and stored probe forces are analytic visualization fixtures, not DFT results.\n"
        "The Cu-Zr fixture is a geometrically conditioned starting distribution, not an equilibrium glass.\n"
        "See each feature page for source, indexing, settings and interpretation.\n")
    print(f"Wrote {len(manifest)} stills and example inputs.")


if __name__ == "__main__":
    main()
